/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package ParserPackage;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int EMPTYSTATE = 8;
  /** RegularExpression Id. */
  int STATE = 9;
  /** RegularExpression Id. */
  int START = 10;
  /** RegularExpression Id. */
  int METHOD = 11;
  /** RegularExpression Id. */
  int CONTRACTOPERATION = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DIGIT>",
    "<LETTER>",
    "<STRING>",
    "\"(_)\"",
    "<STATE>",
    "<START>",
    "<METHOD>",
    "<CONTRACTOPERATION>",
    "\";\"",
    "\"EOF;\"",
    "\":\"",
    "\"(\"",
    "\"|\"",
    "\")\"",
  };

}
