/* Generated By:JavaCC: Do not edit this line. Parser.java */
package parser;
import data.*;
import java.util.*;
import validations.*;
import exceptions.*;
import utils.*;
import types.*;
import ast.*;

@SuppressWarnings("all")
public class Parser implements ParserConstants {

  final public int Start(Hashtable<String, Automaton> auto, ValidationChecks checks) throws ParseException, CustomException, TypingException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case UNDERSCORE:
      DeployTransition(auto,checks);
                                        {if (true) return 0;}
      break;
    case IDWN:
      NormalTransition(auto, checks);
                                           {if (true) return 0;}
      break;
    case 0:
      jj_consume_token(0);
                  {if (true) return 1;}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void DeployTransition(Hashtable<String, Automaton> auto, ValidationChecks checks) throws ParseException, CustomException, TypingException {
        Token iS, eS, isES = null;
        String p;
        Transition t;
        Boolean eC = false;
        ASTNode postC = null;
    iS = jj_consume_token(UNDERSCORE);
    jj_consume_token(LBRACKET);
    jj_consume_token(RBRACKET);
    p = Participant();
    eC = ExternalCall();
    t = DeployAction(auto);
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOL:
    case STRING:
    case SET:
    case MINUS:
    case NOT:
    case TRUE:
    case FALSE:
    case LPAR:
    case SLPAR:
    case EXISTS:
    case FORALL:
    case NUMBER:
    case IDWN:
    case STRING_LITERAL:
      postC = Assertion();
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
    eS = jj_consume_token(IDWN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      isES = jj_consume_token(PLUS);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
        GrammarLogic.addTransition(auto, checks, t, iS, eS, isES, eC, null, postC, p, true);
  }

  final public void NormalTransition(Hashtable<String, Automaton> auto, ValidationChecks checks) throws ParseException, CustomException, TypingException {
        Token iS, eS, isES = null;
        String p;
        Transition t;
        Boolean eC = false;
        ASTNode postC = null, preC = null;
    iS = jj_consume_token(IDWN);
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOL:
    case STRING:
    case SET:
    case MINUS:
    case NOT:
    case TRUE:
    case FALSE:
    case LPAR:
    case SLPAR:
    case EXISTS:
    case FORALL:
    case NUMBER:
    case IDWN:
    case STRING_LITERAL:
      preC = Assertion();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
    p = ParticipantExtra();
    eC = ExternalCall();
    t = NormalAction(auto);
    jj_consume_token(LBRACKET);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOL:
    case STRING:
    case SET:
    case MINUS:
    case NOT:
    case TRUE:
    case FALSE:
    case LPAR:
    case SLPAR:
    case EXISTS:
    case FORALL:
    case NUMBER:
    case IDWN:
    case STRING_LITERAL:
      postC = Assertion();
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    jj_consume_token(RBRACKET);
    eS = jj_consume_token(IDWN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      isES = jj_consume_token(PLUS);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
                GrammarLogic.addTransition(auto, checks, t, iS, eS, isES, eC, preC, postC, p, false);
  }

  final public boolean ExternalCall() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GT:
      jj_consume_token(GT);
               {if (true) return false;}
      break;
    case LT:
      jj_consume_token(LT);
                 {if (true) return true;}
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String Participant() throws ParseException {
        Token p1, p2 = null, p3 = null;
    p1 = jj_consume_token(IDWN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COLON:
      p2 = jj_consume_token(COLON);
      p3 = jj_consume_token(IDWN);
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
                if(p2 == null) { {if (true) return p1.image;} }
                else { {if (true) return p1.image.concat(p2.image).concat(p3.image);} }
    throw new Error("Missing return statement in function");
  }

  final public String ParticipantExtra() throws ParseException {
        String p1, p2;
        Token join;
        Set < String > parts = new HashSet < String > ();
    p1 = Participant();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MOREPART:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_1;
      }
      join = jj_consume_token(MOREPART);
      p2 = Participant();
                                                                   parts.add(join.image.concat(p2));
    }
          {if (true) return p1.concat(String.join("", parts));}
    throw new Error("Missing return statement in function");
  }

  final public Transition DeployAction(Hashtable<String, Automaton> auto) throws ParseException {
        Token c;
        List<Param> param = null;
    jj_consume_token(STARTLABEL);
    jj_consume_token(LPAR);
    c = jj_consume_token(IDWN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      param = ParamList();
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(RPAR);
          {if (true) return new Transition(c.image, "starts", ".", param);}
    throw new Error("Missing return statement in function");
  }

  final public Transition NormalAction(Hashtable<String, Automaton> auto) throws ParseException {
        Token c, aLabel;
        String aType;
        List<Param> param;
    c = jj_consume_token(IDWN);
    aType = OperationType();
    aLabel = jj_consume_token(IDWN);
    jj_consume_token(LPAR);
    param = ParamList();
    jj_consume_token(RPAR);
          {if (true) return new Transition(c.image, aLabel.image, aType, param);}
    throw new Error("Missing return statement in function");
  }

  final public String OperationType() throws ParseException {
        Token aType;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      aType = jj_consume_token(MINUS);
      break;
    case DOT:
      aType = jj_consume_token(DOT);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return aType.image;}
    throw new Error("Missing return statement in function");
  }

//	ASSERTIONS - PARAMETERS
  final public List<Param> ParamList() throws ParseException {
        List<Param> l = new LinkedList<Param>();
        Token x;
        IType t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDWN:
      x = jj_consume_token(IDWN);
      jj_consume_token(COLON);
      t = Type();
                                     l.add(new Param(x.image, t));
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_2;
        }
        jj_consume_token(COMMA);
        x = jj_consume_token(IDWN);
        jj_consume_token(COLON);
        t = Type();
                                             l.add(new Param(x.image, t));
      }
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
          {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public IType Type() throws ParseException {
        IType t;
        Token role;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
                  t = IntType.singleton;
      break;
    case BOOL:
      jj_consume_token(BOOL);
               t = BoolType.singleton;
      break;
    case STRING:
      jj_consume_token(STRING);
                     t = StringType.singleton;
      break;
    case IDWN:
      role = jj_consume_token(IDWN);
                      t = new ParticipantType(role.image);
      break;
    case SET:
      jj_consume_token(SET);
              t = SetType.singleton;
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Assertion() throws ParseException {
        ASTNode n;
    n = Logical();
          {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Logical() throws ParseException {
        ASTNode n1, n2;
    n1 = BooleanExp();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        jj_consume_token(OR);
        n2 = BooleanExp();
                                  n1 = new ASTOr(n1, n2);
        break;
      case AND:
        jj_consume_token(AND);
        n2 = BooleanExp();
                                   n1 = new ASTAnd(n1, n2);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          {if (true) return n1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode BooleanExp() throws ParseException {
        ASTNode n1, n2, n3;
    n1 = Exp();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
      case NEQ:
      case LEQ:
      case GEQ:
      case LT:
      case GT:
      case CONTAINS:
      case VARASS:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        jj_consume_token(EQ);
        n2 = Exp();
                            n1 = new ASTEq(n1, n2);
        break;
      case NEQ:
        jj_consume_token(NEQ);
        n2 = Exp();
                             n1 = new ASTNeq(n1, n2);
        break;
      case LT:
        jj_consume_token(LT);
        n2 = Exp();
                            n1 = new ASTLt(n1, n2);
        break;
      case GT:
        jj_consume_token(GT);
        n2 = Exp();
                            n1 = new ASTGt(n1, n2);
        break;
      case LEQ:
        jj_consume_token(LEQ);
        n2 = Exp();
                             n1 = new ASTLeq(n1, n2);
        break;
      case GEQ:
        jj_consume_token(GEQ);
        n2 = Exp();
                             n1 = new ASTGeq(n1, n2);
        break;
      case VARASS:
        jj_consume_token(VARASS);
        n2 = Exp();
                                n1 = new ASTAssign(n1, n2);
        break;
      case CONTAINS:
        jj_consume_token(CONTAINS);
        n2 = Exp();
                                  {if (true) return new ASTContains(n1, n2);}
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          {if (true) return n1;}
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Exp() throws ParseException {
  ASTNode n1, n2;
    n1 = Unary();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
      case TIMES:
      case DIV:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        n2 = Unary();
                                n1 = new ASTAdd(n1, n2);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        n2 = Unary();
                                 n1 = new ASTSub(n1, n2);
        break;
      case TIMES:
        jj_consume_token(TIMES);
        n2 = Unary();
                                 n1 = new ASTMul(n1, n2);
        break;
      case DIV:
        jj_consume_token(DIV);
        n2 = Unary();
                               n1 = new ASTDiv(n1, n2);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          {if (true) return n1;}
    throw new Error("Missing return statement in function");
  }

/*
	Atomic and negation
*/
  final public ASTNode Unary() throws ParseException {
        ASTNode n1;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOL:
    case STRING:
    case SET:
    case TRUE:
    case FALSE:
    case LPAR:
    case SLPAR:
    case EXISTS:
    case FORALL:
    case NUMBER:
    case IDWN:
    case STRING_LITERAL:
      n1 = Fact();
                      {if (true) return n1;}
      break;
    case MINUS:
      jj_consume_token(MINUS);
      n1 = Unary();
                                 {if (true) return new ASTSub(new ASTNum(0),n1);}
      break;
    case NOT:
      jj_consume_token(NOT);
      n1 = Unary();
                               {if (true) return new ASTNot(n1);}
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode Fact() throws ParseException {
        Token t1, t2;
        ASTNode n1, n2, n3;
        IType ty1 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      t1 = jj_consume_token(NUMBER);
                        {if (true) return new ASTNum(Integer.parseInt(t1.image));}
      break;
    case STRING_LITERAL:
      t1 = jj_consume_token(STRING_LITERAL);
                                  {if (true) return new ASTString(t1.image);}
      break;
    case SLPAR:
      jj_consume_token(SLPAR);
      jj_consume_token(SRPAR);
                            {if (true) return new ASTSet();}
      break;
    case LPAR:
      jj_consume_token(LPAR);
      n1 = Logical();
      jj_consume_token(RPAR);
                                         {if (true) return n1;}
      break;
    case TRUE:
      jj_consume_token(TRUE);
                     {if (true) return new ASTBool(true);}
      break;
    case FALSE:
      jj_consume_token(FALSE);
                      {if (true) return new ASTBool(false);}
      break;
    case EXISTS:
      jj_consume_token(EXISTS);
      n1 = Fact();
      n2 = Fact();
      n3 = Logical();
                                                            {if (true) return new ASTExists(n1, n2, n3);}
      break;
    case FORALL:
      jj_consume_token(FORALL);
      n1 = Fact();
      n2 = Fact();
      n3 = Logical();
                                                            {if (true) return new ASTForAll(n1, n2, n3);}
      break;
    case IDWN:
      t1 = jj_consume_token(IDWN);
                          {if (true) return new ASTId(t1.image);}
      break;
    case INT:
    case BOOL:
    case STRING:
    case SET:
      ty1 = Type();
      t1 = jj_consume_token(IDWN);
                                         {if (true) return new ASTVar(t1.image, ty1);}
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x80000001,0x286022f0,0x100,0x286022f0,0x286022f0,0x100,0x180000,0x0,0x0,0x0,0x200,0x0,0x0,0xf0,0x5000,0x5000,0x11f8000,0x11f8000,0xf00,0xf00,0x286022f0,0x286000f0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x800,0x19c0,0x0,0x19c0,0x19c0,0x0,0x0,0x1,0x10,0x2,0x20,0x2,0x800,0x800,0x0,0x0,0x8,0x8,0x0,0x0,0x19c0,0x19c0,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[45];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 45; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

 }
