/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNDERSCORE = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int LPAR = 8;
  /** RegularExpression Id. */
  int RPAR = 9;
  /** RegularExpression Id. */
  int LCURLB = 10;
  /** RegularExpression Id. */
  int RCURLB = 11;
  /** RegularExpression Id. */
  int NORMALCALL = 12;
  /** RegularExpression Id. */
  int EXTERNALCALL = 13;
  /** RegularExpression Id. */
  int MOREPART = 14;
  /** RegularExpression Id. */
  int STARTLABEL = 15;
  /** RegularExpression Id. */
  int OPERATIONTYPE = 16;
  /** RegularExpression Id. */
  int STRING = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"_\"",
    "\"+\"",
    "\":\"",
    "<NUMBER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\">\"",
    "\"<\"",
    "\"|\"",
    "\"starts\"",
    "<OPERATIONTYPE>",
    "<STRING>",
  };

}
